# Usamos una imagen ligera de Node 20
FROM node:20-alpine

# Instalamos herramientas básicas para el sistema operativo del contenedor
RUN apk add --no-cache git bash

# Habilitamos corepack para manejar pnpm de forma nativa y rápida
RUN corepack enable && corepack prepare pnpm@latest --activate

# Establecemos el directorio de trabajo
WORKDIR /app

# Exponemos el puerto de Vite (5173), el de la API (3000), y Metro (8081)
EXPOSE 5173 3000 8081

# Comando por defecto para mantener el contenedor vivo
CMD ["tail", "-f", "/dev/null"]
